name = "Wordle"
authors = ["Douglas G. Moore <doug@dglmoore.com>"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
DrWatson = "2.9.1"
julia = "1.7.2"
